TITANIC DATASET  (WHETHER THE PASSENGER WILL BE ALIVE OR NOT)

In [37]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [38]:
df = pd.read_csv('train.csv')
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [39]:
df1 = pd.read_csv('train.csv', usecols = ['Age','Sex','Pclass','Survived'])
df1.head()

Survived  Pclass     Sex   Age
0         0       3    male  22.0
1         1       1  female  38.0
2         1       3  female  26.0
3         1       1  female  35.0
4         0       3    male  35.0

In [40]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [41]:
df1['Age'].isna().sum()/df1.shape[0]

0.19865319865319866

In [42]:
df1 = df1.dropna(subset=['Age'])

In [43]:
df1['Sex'].unique()


array(['male', 'female'], dtype=object)

In [44]:
x = df1.copy()
y = df1['Survived']

In [45]:

from sklearn.preprocessing import OneHotEncoder
ohe1 = OneHotEncoder(drop='first',sparse=False)
x_new = ohe1.fit_transform(x[['Sex']])



c:\Users\91983\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [46]:
x_new

array([[1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],

In [47]:
z = np.hstack((x[['Pclass','Sex','Age']].values,x_new))

In [48]:
z = np.delete(z,1,1)
z

array([[3, 22.0, 1.0],
       [1, 38.0, 0.0],
       [3, 26.0, 0.0],
       ...,
       [1, 19.0, 0.0],
       [1, 26.0, 1.0],
       [3, 32.0, 1.0]], dtype=object)

In [49]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(z,y,test_size=0.25,random_state=0)
x_train

array([[2, 7.0, 0.0],
       [3, 45.0, 1.0],
       [3, 21.0, 1.0],
       ...,
       [1, 46.0, 1.0],
       [3, 26.0, 1.0],
       [1, 45.0, 0.0]], dtype=object)

In [50]:
x_test

array([[3, 28.0, 0.0],
       [1, 50.0, 0.0],
       [1, 0.92, 1.0],
       [2, 36.0, 1.0],
       [1, 26.0, 1.0],
       [3, 36.0, 1.0],
       [2, 31.0, 1.0],
       [1, 65.0, 1.0],
       [1, 65.0, 1.0],
       [1, 47.0, 1.0],
       [3, 22.0, 1.0],
       [3, 26.0, 0.0],
       [3, 4.0, 0.0],
       [3, 39.0, 1.0],
       [2, 21.0, 1.0],
       [2, 55.0, 0.0],
       [2, 33.0, 1.0],
       [3, 0.75, 0.0],
       [3, 24.0, 0.0],
       [2, 39.0, 1.0],
       [3, 20.0, 1.0],
       [2, 40.0, 0.0],
       [2, 14.0, 0.0],
       [3, 29.0, 1.0],
       [3, 30.0, 1.0],
       [3, 0.75, 0.0],
       [1, 36.0, 0.0],
       [2, 21.0, 1.0],
       [1, 27.0, 1.0],
       [3, 40.0, 0.0],
       [3, 32.0, 1.0],
       [3, 2.0, 1.0],
       [3, 20.0, 1.0],
       [1, 52.0, 0.0],
       [3, 35.0, 1.0],
       [3, 42.0, 1.0],
       [1, 38.0, 0.0],
       [1, 36.0, 1.0],
       [3, 20.0, 1.0],
       [3, 15.0, 0.0],
       [3, 22.0, 1.0],
       [3, 21.0, 1.0],
       [1, 42.0, 1.0],
       [1, 21

* StandardScaler removes the mean and scales each feature/variable to unit variance. This operation is performed feature-wise in an independent  way. StandardScaler can be influenced by outliers (if they exist in the dataset)
* The fit(data) method is used to compute the mean and std dev for a given feature to be used further for scaling.
* The transform(data) method is used to perform scaling using mean and std dev calculated using the .fit() method.

In [51]:
from sklearn.preprocessing import StandardScaler  
st = StandardScaler()
x_train = st.fit_transform(x_train)
x_test = st.transform(x_test)
x_train


array([[-0.30879361, -1.56807581, -1.33117269],
       [ 0.89707924,  1.05758227,  0.75121734],
       [ 0.89707924, -0.6007281 ,  0.75121734],
       ...,
       [-1.51466646,  1.12667854,  0.75121734],
       [ 0.89707924, -0.25524677,  0.75121734],
       [-1.51466646,  1.05758227, -1.33117269]])

SUPPORT VECTOR MACHINE

In [52]:
from sklearn.svm import SVC
svc = SVC(kernel='linear',random_state=0)
svc.fit(x_train,y_train)

SVC(kernel='linear', random_state=0)

In [53]:
y_pred = svc.predict(x_test)
y_pred

array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 0], dtype=int64)

In [54]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import sklearn.metrics as sm
cmp = confusion_matrix(y_test,y_pred)
cmp

array([[87, 16],
       [24, 52]], dtype=int64)

In [55]:
print("accuracy : ",(accuracy_score(y_test,y_pred))*100)

accuracy :  77.6536312849162


LINEAR REGRESSION 


In [56]:
from sklearn.linear_model import LinearRegression

In [57]:
regressor = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression()

In [58]:
x_train1,x_test1,y_train1,y_test1 = train_test_split(z,y,test_size=0.25,random_state=0)
x_train1

array([[2, 7.0, 0.0],
       [3, 45.0, 1.0],
       [3, 21.0, 1.0],
       ...,
       [1, 46.0, 1.0],
       [3, 26.0, 1.0],
       [1, 45.0, 0.0]], dtype=object)

In [59]:
regressor.fit(x_train1,y_train1)

LinearRegression()

In [60]:
y_pred1 = regressor.predict(x_test1)
y_pred1

array([ 5.60452616e-01,  8.49183810e-01,  6.47906564e-01,  2.45817705e-01,
        5.07635309e-01,  3.99296277e-02,  2.73782468e-01,  2.89510152e-01,
        2.89510152e-01,  3.90183302e-01,  1.18230966e-01,  5.71638521e-01,
        6.94683482e-01,  2.31507695e-02,  3.29711996e-01,  6.15330969e-01,
        2.62596563e-01,  7.12860578e-01,  5.82824427e-01,  2.29038846e-01,
        1.29416871e-01,  6.99225260e-01,  8.44642031e-01,  7.90802968e-02,
        7.34873441e-02,  7.12860578e-01,  9.27485148e-01,  3.29711996e-01,
        5.02042356e-01,  4.93337183e-01,  6.23014386e-02,  2.30090021e-01,
        1.29416871e-01,  8.37997904e-01,  4.55225804e-02,  6.37191124e-03,
        9.16299242e-01,  4.51705782e-01,  1.29416871e-01,  6.33161001e-01,
        1.18230966e-01,  1.23823919e-01,  4.18148065e-01,  5.35600073e-01,
        8.46732496e-02,  6.89090529e-01,  2.24497068e-01,  3.12933138e-01,
        4.55225804e-02,  8.46732496e-02,  4.40519876e-01,  7.88712504e-01,
        3.07340185e-01,  

In [61]:
print("accuracy_score Linear regression : ",sm.r2_score(y_test1,y_pred1)*100) 

accuracy_score Linear regression :  37.71225804928526


K - Nearest Neighbors Algorithem

In [62]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=4, metric='minkowski', p=2) # n_neighbors = number nearest neighbors , p = Euclidean metric
classifier.fit(x_train,y_train)                     # Euclidean distance = distance between the best fit line and the nearest points.

KNeighborsClassifier(n_neighbors=4)

In [63]:
y_pred2 = classifier.predict(x_test)
y_pred2

array([1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 1], dtype=int64)

In [64]:
print("accuracy_score KNN regression : ",sm.r2_score(y_test,y_pred2)*100) 

accuracy_score KNN regression :  15.393459376596796


In [65]:
print("accuracy_score KNN regression : ",sm.r2_score(y_test,y_pred2)*100) 
confi_KNN = confusion_matrix(y_test,y_pred)
confi_KNN

accuracy_score KNN regression :  15.393459376596796


array([[87, 16],
       [24, 52]], dtype=int64)

LOGISTIC REGRESSION with standard scaling

In [66]:
from sklearn.linear_model import LogisticRegression
logi_classi = LogisticRegression(random_state=0)
logi_classi.fit(x_train1, y_train1)      

LogisticRegression(random_state=0)

In [67]:
y_pred_logi = logi_classi.predict(x_test1)
y_pred_logi

array([1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 0], dtype=int64)

In [68]:
print("accuracy_score KNN regression : ",sm.r2_score(y_test1,y_pred_logi)*100)

accuracy_score KNN regression :  26.82677567705669


In [69]:
confi_Logi = confusion_matrix(y_test1,y_pred_logi)
confi_Logi

array([[88, 15],
       [17, 59]], dtype=int64)

LOGISTIC REGRESSION without standard scaling

In [70]:
logi_classi = LogisticRegression(random_state=0)
logi_classi.fit(x_train, y_train)     

LogisticRegression(random_state=0)

In [71]:
y_pred_ = logi_classi.predict(x_test)
y_pred_

array([1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 0], dtype=int64)

In [72]:
print("accuracy_score KNN regression : ",sm.r2_score(y_test,y_pred_)*100)

accuracy_score KNN regression :  24.54011241696471
