In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt
import seaborn as sb
import warnings
warnings.filterwarnings("ignore")

In [2]:
data = pd.read_csv("darwin.csv")
data

ID  air_time1  disp_index1  gmrt_in_air1  gmrt_on_paper1  \
0      id_1       5160     0.000013    120.804174       86.853334   
1      id_2      51980     0.000016    115.318238       83.448681   
2      id_3       2600     0.000010    229.933997      172.761858   
3      id_4       2130     0.000010    369.403342      183.193104   
4      id_5       2310     0.000007    257.997131      111.275889   
..      ...        ...          ...           ...             ...   
169  id_170       2930     0.000010    241.736477      176.115957   
170  id_171       2140     0.000009    274.728964      234.495802   
171  id_172       3830     0.000008    151.536989      171.104693   
172  id_173       1760     0.000008    289.518195      196.411138   
173  id_174       2875     0.000008    235.769350      178.208024   

     max_x_extension1  max_y_extension1  mean_acc_in_air1  mean_acc_on_paper1  \
0                 957              6601          0.361800            0.217459   
1                1694              6998          0.272513            0.144880   
2                2333              5802          0.387020            0.181342   
3                1756              8159          0.556879            0.164502   
4                 987              4732          0.266077            0.145104   
..                ...               ...               ...                 ...   
169              1839              6439          0.253347            0.174663   
170              2053              8487          0.225537            0.174920   
171              1287              7352          0.165480            0.161058   
172              1674              6946          0.518937            0.202613   
173              1838              6560          0.567311            0.147818   

     mean_gmrt1  ...  mean_jerk_in_air25  mean_jerk_on_paper25  \
0    103.828754  ...            0.141434              0.024471   
1     99.383459  ...            0.049663              0.018368   
2    201.347928  ...            0.178194              0.017174   
3    276.298223  ...            0.113905              0.019860   
4    184.636510  ...            0.121782              0.020872   
..          ...  ...                 ...                   ...   
169  208.926217  ...            0.119152              0.020909   
170  254.612383  ...            0.174495              0.017640   
171  161.320841  ...            0.114472              0.017194   
172  242.964666  ...            0.114472              0.017194   
173  206.988687  ...            0.114472              0.017194   

     mean_speed_in_air25  mean_speed_on_paper25  num_of_pendown25  \
0               5.596487               3.184589                71   
1               1.665973               0.950249               129   
2               4.000781               2.392521                74   
3               4.206746               1.613522               123   
4               3.319036               1.680629                92   
..                   ...                    ...               ...   
169             4.508709               2.233198                96   
170             4.685573               2.806888                84   
171             3.493815               2.510601                88   
172             3.493815               2.510601                88   
173             3.493815               2.510601                88   

     paper_time25  pressure_mean25  pressure_var25  total_time25  class  
0           40120      1749.278166     296102.7676        144605      P  
1          126700      1504.768272     278744.2850        298640      P  
2           45480      1431.443492     144411.7055         79025      P  
3           67945      1465.843329     230184.7154        181220      P  
4           37285      1841.702561     158290.0255         72575      P  
..            ...              ...             ...           ...    ...  
169         44545      1798.923336     247448.3108         80335   

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 174 entries, 0 to 173
Columns: 452 entries, ID to class
dtypes: float64(300), int64(150), object(2)
memory usage: 614.6+ KB


In [4]:
data.isna().sum().head(20)

ID                      0
air_time1               0
disp_index1             0
gmrt_in_air1            0
gmrt_on_paper1          0
max_x_extension1        0
max_y_extension1        0
mean_acc_in_air1        0
mean_acc_on_paper1      0
mean_gmrt1              0
mean_jerk_in_air1       0
mean_jerk_on_paper1     0
mean_speed_in_air1      0
mean_speed_on_paper1    0
num_of_pendown1         0
paper_time1             0
pressure_mean1          0
pressure_var1           0
total_time1             0
air_time2               0
dtype: int64

In [5]:
data .describe()

air_time1  disp_index1  gmrt_in_air1  gmrt_on_paper1  \
count     174.000000   174.000000    174.000000      174.000000   
mean     5664.166667     0.000010    297.666685      200.504413   
std     12653.772746     0.000003    183.943181      111.629546   
min        65.000000     0.000002     28.734515       29.935835   
25%      1697.500000     0.000008    174.153023      136.524742   
50%      2890.000000     0.000009    255.791452      176.494494   
75%      4931.250000     0.000011    358.917885      234.052560   
max    109965.000000     0.000028   1168.328276      865.210522   

       max_x_extension1  max_y_extension1  mean_acc_in_air1  \
count        174.000000        174.000000        174.000000   
mean        1977.965517       7323.896552          0.416374   
std         1648.306365       2188.290512          0.381837   
min          754.000000        561.000000          0.067748   
25%         1362.500000       6124.000000          0.218209   
50%         1681.000000       6975.500000          0.275184   
75%         2082.750000       8298.500000          0.442706   
max        18602.000000      15783.000000          2.772566   

       mean_acc_on_paper1  mean_gmrt1  mean_jerk_in_air1  ...  mean_gmrt25  \
count          174.000000  174.000000         174.000000  ...   174.000000   
mean             0.179823  249.085549           0.067556  ...   221.360646   
std              0.064693  132.698462           0.074776  ...    63.762013   
min              0.096631   41.199445           0.011861  ...    69.928033   
25%              0.146647  161.136182           0.029523  ...   178.798382   
50%              0.163659  224.445268           0.039233  ...   217.431621   
75%              0.188879  294.392298           0.071057  ...   264.310776   
max              0.627350  836.784702           0.543199  ...   437.373267   

       mean_jerk_in_air25  mean_jerk_on_paper25  mean_speed_in_air25  \
count          174.000000            174.000000           174.000000   
mean             0.148286              0.019934             4.472643   
std              0.062207              0.002388             1.501411   
min              0.030169              0.014987             1.323565   
25%              0.107732              0.018301             3.485934   
50%              0.140483              0.019488             4.510578   
75%              0.199168              0.021134             5.212794   
max              0.375078              0.029227            10.416715   

       mean_speed_on_paper25  num_of_pendown25   paper_time25  \
count             174.000000        174.000000     174.000000   
mean                2.871613         85.839080   43109.712644   
std                 0.852809         27.485518   19092.024337   
min                 0.950249         32.000000   15930.000000   
25%                 2.401199         66.000000   32803.750000   
50%                 2.830672         81.000000   37312.500000   
75%                 3.335828        101.500000   46533.750000   
max                 5.602909        209.000000  139575.000000   

       pressure_mean25  pressure_var25  total_time25  
count       174.000000      174.000000  1.740000e+02  
mean       1629.585962   163061.767360  1.642033e+05  
std         324.142316    56845.610814  4.969397e+05  
min         474.049462    26984.926660  2.998000e+04  
25%        1499.112088   120099.046800  5.917500e+04  
50%        1729.385010   158236.771800  7.611500e+04  
75%        1865.626974   200921.078475  1.275425e+05  
max        1999.775983   352981.850000  5.704200e+06  

[8 rows x 450 columns]

In [6]:
data = data.sample(frac=1).reset_index(drop=True)

In [7]:
y = data.iloc[:,[-1]]
x= data.iloc[:,1:451]
x

air_time1  disp_index1  gmrt_in_air1  gmrt_on_paper1  max_x_extension1  \
0          980     0.000008    250.521841      184.767136              1850   
1         1285     0.000009    359.163772      162.140814              1250   
2         1510     0.000007    284.015654      154.783882              2883   
3         2915     0.000010    202.945687      172.225169              1296   
4          890     0.000010    412.031903      264.431867              1877   
..         ...          ...           ...             ...               ...   
169       5160     0.000013    120.804174       86.853334               957   
170       3845     0.000010    130.925954      232.722833              1976   
171       1765     0.000008    255.368912      222.682673              2397   
172       2975     0.000009    396.225929      153.497310              1628   
173       4015     0.000011    179.573489      172.444594              2167   

     max_y_extension1  mean_acc_in_air1  mean_acc_on_paper1  mean_gmrt1  \
0                4617          0.216186            0.180359  217.644488   
1                6881          0.237090            0.166215  260.652293   
2                4663          0.668661            0.168026  219.399768   
3                6818          0.219212            0.146434  187.585428   
4                6801          0.340128            0.187452  338.231885   
..                ...               ...                 ...         ...   
169              6601          0.361800            0.217459  103.828754   
170              8176          0.203339            0.167934  181.824394   
171              7306          0.238215            0.169453  239.025792   
172              7466          0.602640            0.148833  274.861619   
173              7179          0.182736            0.150301  176.009041   

     mean_jerk_in_air1  ...  mean_gmrt25  mean_jerk_in_air25  \
0             0.033126  ...   119.711264            0.041426   
1             0.035756  ...   240.740253            0.135469   
2             0.123317  ...   200.573686            0.100256   
3             0.029357  ...   121.293539            0.056777   
4             0.058966  ...   158.018354            0.089514   
..                 ...  ...          ...                 ...   
169           0.051836  ...   249.729085            0.141434   
170           0.026983  ...   199.628721            0.114529   
171           0.039105  ...   310.818279            0.204778   
172           0.099270  ...   407.395427            0.375078   
173           0.025536  ...   196.994687            0.114875   

     mean_jerk_on_paper25  mean_speed_in_air25  mean_speed_on_paper25  \
0                0.016080             1.724092               1.592610   
1                0.020711             4.954802               2.893938   
2                0.024975             4.086628               3.047974   
3                0.016147             1.915654               1.895614   
4                0.018764             3.136146               2.172971   
..                    ...                  ...                    ...   
169              0.024471             5.596487               3.184589   
170              0.017876             3.268645               3.221813   
171              0.021942             6.798118               4.203383   
172              0.022148             8.964604               5.292562   
173              0.019682             3.684590               2.794757   

     num_of_pendown25  paper_time25  pressure_mean25  pressure_var25  \
0                 209        102435      1305.883145    291397.25010   
1                  81         34200      1867.641082    144583.04270   
2                  57         27660      1783.093999    183403.14590   
3                  88         50805      1412.871469    202272.66730   
4                 125         60085      1057.709495    209005.88160   
..                ...           ...              ...             ...   
169  

In [8]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(drop='first',sparse=False)
y_new = encoder.fit_transform(y)
y = pd.DataFrame(y_new,columns = y.columns)
y

class
0      0.0
1      0.0
2      1.0
3      1.0
4      1.0
..     ...
169    1.0
170    1.0
171    0.0
172    0.0
173    1.0

[174 rows x 1 columns]

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=1,test_size=0.20)
x_train

air_time1  disp_index1  gmrt_in_air1  gmrt_on_paper1  max_x_extension1  \
90        5975     0.000005    468.028309      254.541305              1443   
89        1920     0.000011    199.764957      109.902254              1548   
127        845     0.000009    319.136372      148.979549              1328   
118       7770     0.000007    252.920870      241.011868              2076   
48        7870     0.000012    102.981366       79.647541              1420   
..         ...          ...           ...             ...               ...   
133        900     0.000007    689.164667      412.093973              3937   
137       1370     0.000007    377.251255      322.546230              1718   
72        3940     0.000012    141.251407       80.975585              1352   
140       4410     0.000011    170.472145      132.929749              1910   
37        1755     0.000012    413.554928      219.636991              1692   

     max_y_extension1  mean_acc_in_air1  mean_acc_on_paper1  mean_gmrt1  \
90               6013          2.772566            0.170472  361.284807   
89               6260          0.212523            0.143013  154.833606   
127              5488          0.250414            0.140594  234.057960   
118              5683          0.498263            0.193680  246.966369   
48               6142          0.320674            0.156004   91.314453   
..                ...               ...                 ...         ...   
133              8474          0.943476            0.339286  550.629320   
137              8347          0.218833            0.264510  349.898743   
72               6373          0.208305            0.128361  111.113496   
140              8502          0.222532            0.139789  151.700947   
37               9074          0.272219            0.169035  316.595959   

     mean_jerk_in_air1  ...  mean_gmrt25  mean_jerk_in_air25  \
90            0.543199  ...   221.582225            0.107756   
89            0.028369  ...   159.327265            0.131135   
127           0.044115  ...   198.486673            0.107724   
118           0.084725  ...   286.213565            0.231913   
48            0.054545  ...   184.145435            0.080464   
..                 ...  ...          ...                 ...   
133           0.158460  ...   196.454216            0.106495   
137           0.030856  ...   133.762847            0.069642   
72            0.033436  ...   294.388363            0.154073   
140           0.032345  ...   119.130593            0.048751   
37            0.038039  ...   200.818371            0.156055   

     mean_jerk_on_paper25  mean_speed_in_air25  mean_speed_on_paper25  \
90               0.020231             4.298868               2.999059   
89               0.018907             3.643543               1.667827   
127              0.020837             3.556917               3.078715   
118              0.020821             6.278983               3.277159   
48               0.017964             3.053848               2.758524   
..                    ...                  ...                    ...   
133              0.018960             3.930293               2.560737   
137              0.016373             2.763884               1.524188   
72               0.019995             6.793587               2.912826   
140              0.019785             2.293897               1.274208   
37               0.018010             4.699902               2.121379   

     num_of_pendown25  paper_time25  pressure_mean25  pressure_var25  \
90                 72         30395      1727.875637     187862.8199   
89                 76         43790      1081.054579     152045.4446   
127                69         28295      1455.754197     238345.1474   
118                58         33560      1840.851162     144392.4464   
48                 74         41340       878.310595     202783.1691   
..                ...           ...              ...             ...   
133  

In [10]:
from sklearn.linear_model import LinearRegression   #  WITHOUT STANDARIZATION
regressor = LinearRegression()
regressor.fit(x_train,y_train)
y_pred = regressor.predict(x_test)
import sklearn.metrics as sm
print("accuracy : ", (sm.r2_score(y_test,y_pred)))

accuracy :  -22.20295233323905


In [11]:
for i in range(1,5):
    data = pd.read_csv("darwin.csv")
    data = data.sample(frac=1).reset_index(drop=True)
    y = data.iloc[:,[-1]]
    x= data.iloc[:,1:451]
    ts = 0.10*i
    from sklearn.preprocessing import OneHotEncoder
    encoder = OneHotEncoder(drop='first',sparse=False)
    y_new = encoder.fit_transform(y)
    y = pd.DataFrame(y_new,columns = y.columns)
    from sklearn.preprocessing import StandardScaler
    scaler = StandardScaler()
    x = scaler.fit_transform(x)
    from sklearn.model_selection import train_test_split
    x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=0,test_size=ts)
    from sklearn.linear_model import LinearRegression   #  WITHOUT STANDARIZATION
    regressor = LinearRegression()
    regressor.fit(x_train,y_train)
    y_pred = regressor.predict(x_test)
    import sklearn.metrics as sm
    print("accuracy : ", (sm.r2_score(y_test,y_pred)))

accuracy :  -0.27562686429799244
accuracy :  -0.09764903369147704
accuracy :  0.28510738760294063
accuracy :  0.24152100940670018


In [12]:
for i in range(1,5):
    data = pd.read_csv("darwin.csv")
    data = data.sample(frac=1).reset_index(drop=True)
    y = data.iloc[:,[-1]]
    x= data.iloc[:,1:451]
    ts = 0.10*i
    from sklearn.preprocessing import OneHotEncoder
    encoder = OneHotEncoder(drop='first',sparse=False)
    y_new = encoder.fit_transform(y)
    y = pd.DataFrame(y_new,columns = y.columns)
    from sklearn.preprocessing import StandardScaler
    scaler = StandardScaler()
    x = scaler.fit_transform(x)
    from sklearn.model_selection import train_test_split
    x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=0,test_size=ts)
    from sklearn.linear_model import LogisticRegression   #  WITHOUT STANDARIZATION
    logi_regressor = LogisticRegression()
    logi_regressor.fit(x_train,y_train)
    y_pred = logi_regressor.predict(x_test)
    import sklearn.metrics as sm
    print("accuracy : ", (sm.r2_score(y_test,y_pred))*100)
    from sklearn.metrics import confusion_matrix
    gv = confusion_matrix(y_test,y_pred)
    print(gv)
    

accuracy :  32.50000000000001
[[8 2]
 [1 7]]
accuracy :  53.33333333333332
[[19  1]
 [ 3 12]]
accuracy :  35.757575757575765
[[18  2]
 [ 6 27]]
accuracy :  24.166666666666682
[[24  6]
 [ 7 33]]


In [13]:
for i in range(1,5):
    data = pd.read_csv("darwin.csv")
    data = data.sample(frac=1).reset_index(drop=True)
    y = data.iloc[:,[-1]]
    x= data.iloc[:,1:451]
    ts = 0.10*i
    from sklearn.preprocessing import OneHotEncoder
    encoder = OneHotEncoder(drop='first',sparse=False)
    y_new = encoder.fit_transform(y)
    y = pd.DataFrame(y_new,columns = y.columns)
    from sklearn.preprocessing import StandardScaler
    scaler = StandardScaler()
    x = scaler.fit_transform(x)
    from sklearn.model_selection import train_test_split
    x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=0,test_size=ts)
    from sklearn.neighbors import KNeighborsClassifier
    classifier = KNeighborsClassifier(n_neighbors=10) # n_neighbors = number nearest neighbors , p = Euclidean metric
    classifier.fit(x_train,y_train)                     # Euclidean distance = distance between the best fit line and the nearest points.
    y_pred = classifier.predict(x_test)
    import sklearn.metrics as sm
    print("accuracy : ", (sm.r2_score(y_test,y_pred)))
    from sklearn.metrics import confusion_matrix
    gv = confusion_matrix(y_test,y_pred)
    print(gv)
    

accuracy :  -0.4025974025974024
[[11  0]
 [ 6  1]]
accuracy :  -0.49671052631578894
[[16  0]
 [13  6]]
accuracy :  -0.5991379310344827
[[24  0]
 [21  8]]
accuracy :  -0.2158808933002485
[[39  0]
 [21 10]]


In [14]:
for i in range(1,5):
    data = pd.read_csv("darwin.csv")
    data = data.sample(frac=1).reset_index(drop=True)
    y = data.iloc[:,[-1]]
    x= data.iloc[:,1:451]
    ts = 0.10*i
    from sklearn.preprocessing import OneHotEncoder
    encoder = OneHotEncoder(drop='first',sparse=False)
    y_new = encoder.fit_transform(y)
    y = pd.DataFrame(y_new,columns = y.columns)
    from sklearn.preprocessing import StandardScaler
    scaler = StandardScaler()
    x = scaler.fit_transform(x)
    from sklearn.model_selection import train_test_split
    x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=0,test_size=ts)
    from sklearn.neighbors import KNeighborsClassifier
    classifier = KNeighborsClassifier(n_neighbors=10) # n_neighbors = number nearest neighbors , p = Euclidean metric
    classifier.fit(x_train,y_train)                     # Euclidean distance = distance between the best fit line and the nearest points.
    y_pred = classifier.predict(x_test)
    import sklearn.metrics as sm
    print("accuracy : ", (sm.r2_score(y_test,y_pred)))
    from sklearn.metrics import confusion_matrix
    gv = confusion_matrix(y_test,y_pred)
    print(gv)

accuracy :  -1.0
[[6 0]
 [8 4]]
accuracy :  -0.7269736842105261
[[16  0]
 [15  4]]
accuracy :  -0.5099715099715101
[[26  0]
 [20  7]]
accuracy :  -0.5542763157894741
[[32  0]
 [27 11]]


In [15]:
for i in range(1,5):
    data = pd.read_csv("darwin.csv")
    data = data.sample(frac=1).reset_index(drop=True)
    y = data.iloc[:,[-1]]
    x= data.iloc[:,1:451]
    ts = 0.10*i
    from sklearn.preprocessing import OneHotEncoder
    encoder = OneHotEncoder(drop='first',sparse=False)
    y_new = encoder.fit_transform(y)
    y = pd.DataFrame(y_new,columns = y.columns)
    from sklearn.preprocessing import StandardScaler
    scaler = StandardScaler()
    x = scaler.fit_transform(x)
    from sklearn.model_selection import train_test_split
    x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=0,test_size=ts)
    from sklearn.linear_model import Lasso
    lasso_regressor = Lasso(alpha=0.3)
    lasso_regressor.fit(x_train,y_train)
    y_pred = lasso_regressor.predict(x_test)
    import sklearn.metrics as sm
    print("accuracy : ", (sm.r2_score(y_test,y_pred))*100)
    

accuracy :  -0.9781804733727473
accuracy :  -13.16747276324941
accuracy :  -7.360699812333915
accuracy :  -9.136156311637066
